management:
  endpoints:
    web:
      exposure:
        include:
          - cosid
          - cosidGenerator
          - cosidStringGenerator
          - health
  endpoint:
    health:
      show-details: always
springdoc:
  show-actuator: true
server:
  port: 8601
spring:
  application:
    name: ${service.name:cosid-example-redis}
  data:
    redis:
      host: localhost
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  generator:
    enabled: true
  snowflake:
    enabled: true
    share:
      enabled: false
    provider:
      snowflake_friendly:
        converter:
          type: snowflake_friendly
      snowflake_orderly_friendly:
        converter:
          type: snowflake_friendly
          friendly:
            pad-start: true
      snowflake_short_id:
        converter:
          type: radix
          radix:
            char-size: 11
            pad-start: true
      snowflake_friendly_second:
        timestamp-unit: second
        epoch: 1577203200
        timestamp-bit: 31
        machine-bit: 10
        sequence-bit: 22
        converter:
          type: snowflake_friendly
  segment:
    enabled: true
    mode: chain
    distributor:
      type: redis
    share:
      enabled: false
    provider:
      biz_prefix_no:
        offset: 2000000000
        converter:
          type: to_string
          prefix: BIZ
          to-string:
            char-size: 10
            pad-start: true
      date_prefix_no:
        converter:
          type: to_string
          prefix: BIZ-
          date-prefix:
            enabled: true
            pattern: yyMMdd
      no_suffix_biz:
        offset: 2000000000
        converter:
          type: to_string
          suffix: BIZ
          to-string:
            char-size: 10
            pad-start: true
      biz_prefix_radix:
        offset: 2000000000
        converter:
          type: radix
          prefix: BIZ
          radix:
            char-size: 6
            pad-start: true
      biz_prefix_radix36:
        converter:
          type: radix36
          prefix: BIZ
          radix36:
            char-size: 8
            pad-start: true
      group_year_biz:
        group:
          by: year
          pattern: yyyy
        converter:
          type: to_string
          to-string:
            pad-start: true
            char-size: 8
          prefix: BIZ-
          group-prefix:
            enabled: true
      group_year_month_biz:
        group:
          by: year_month
          pattern: yyyyMM
        converter:
          type: to_string
          to-string:
            pad-start: true
            char-size: 8
          prefix: BIZ-
          group-prefix:
            enabled: true
      group_year_month_day_biz:
        group:
          by: year_month_day
          pattern: yyMMdd
        converter:
          type: to_string
          to-string:
            pad-start: true
            char-size: 8
          prefix: BIZ-
          group-prefix:
            enabled: true
logging:
  level:
    me.ahoo.cosid: debug

